import { AlertProtocol, ForecastDay, WardRecord, ZoneSummary } from './types';

export const CHENNAI_ZONES: ZoneSummary[] = [
  { zone_id: 1, zone_name: 'Thiruvottiyur', region: 'North', total_wards: 14, total_derived_pop: 274800, max_risk_level: 'High', avg_htsi: 61.4, hwc_count: 8 },
  { zone_id: 2, zone_name: 'Manali', region: 'North', total_wards: 7, total_derived_pop: 138500, max_risk_level: 'Moderate', avg_htsi: 58.2, hwc_count: 5 },
  { zone_id: 3, zone_name: 'Madhavaram', region: 'North', total_wards: 12, total_derived_pop: 242000, max_risk_level: 'Moderate', avg_htsi: 59.5, hwc_count: 7 },
  { zone_id: 4, zone_name: 'Tondiarpet', region: 'North', total_wards: 15, total_derived_pop: 384000, max_risk_level: 'Very High', avg_htsi: 69.8, hwc_count: 12 },
  { zone_id: 5, zone_name: 'Royapuram', region: 'North', total_wards: 15, total_derived_pop: 442000, max_risk_level: 'Very High', avg_htsi: 72.1, hwc_count: 14 },
  { zone_id: 6, zone_name: 'Thiru-Vi-Ka Nagar', region: 'Central', total_wards: 15, total_derived_pop: 410000, max_risk_level: 'Very High', avg_htsi: 70.4, hwc_count: 13 },
  { zone_id: 7, zone_name: 'Ambattur', region: 'North', total_wards: 15, total_derived_pop: 360000, max_risk_level: 'High', avg_htsi: 64.2, hwc_count: 10 },
  { zone_id: 8, zone_name: 'Anna Nagar', region: 'Central', total_wards: 15, total_derived_pop: 395000, max_risk_level: 'High', avg_htsi: 65.8, hwc_count: 11 },
  { zone_id: 9, zone_name: 'Teynampet', region: 'Central', total_wards: 18, total_derived_pop: 480000, max_risk_level: 'Very High', avg_htsi: 71.0, hwc_count: 15 },
  { zone_id: 10, zone_name: 'Kodambakkam', region: 'Central', total_wards: 16, total_derived_pop: 375000, max_risk_level: 'High', avg_htsi: 66.5, hwc_count: 11 },
  { zone_id: 11, zone_name: 'Valasaravakkam', region: 'South', total_wards: 13, total_derived_pop: 228000, max_risk_level: 'Moderate', avg_htsi: 59.8, hwc_count: 7 },
  { zone_id: 12, zone_name: 'Alandur', region: 'South', total_wards: 12, total_derived_pop: 215000, max_risk_level: 'Moderate', avg_htsi: 58.4, hwc_count: 6 },
  { zone_id: 13, zone_name: 'Adyar', region: 'South', total_wards: 13, total_derived_pop: 278000, max_risk_level: 'Moderate', avg_htsi: 60.1, hwc_count: 9 },
  { zone_id: 14, zone_name: 'Perungudi', region: 'South', total_wards: 11, total_derived_pop: 182000, max_risk_level: 'Moderate', avg_htsi: 57.6, hwc_count: 6 },
  { zone_id: 15, zone_name: 'Sholinganallur', region: 'South', total_wards: 9, total_derived_pop: 142204, max_risk_level: 'Normal', avg_htsi: 52.3, hwc_count: 6 }
];

export const ERA5_GRIDS = [
  { grid_id: 'grid_13.2_80.2', lat: 13.2, lon: 80.2, label: 'North Suburbs (Thiruvottiyur/Manali)', status: 'Land Active' },
  { grid_id: 'grid_13.1_80.2', lat: 13.1, lon: 80.2, label: 'North Urban Core (Royapuram/Tondiarpet)', status: 'Land Active' },
  { grid_id: 'grid_13.0_80.2', lat: 13.0, lon: 80.2, label: 'Central Urban Core (Anna Nagar/Teynampet)', status: 'Land Active' },
  { grid_id: 'grid_12.9_80.2', lat: 12.9, lon: 80.2, label: 'South Urban (Adyar/Alandur/Velachery)', status: 'Land Active' },
  { grid_id: 'grid_12.8_80.2', lat: 12.8, lon: 80.2, label: 'South Coastal (Sholinganallur/OMR)', status: 'Land Active' }
];

export const WARDS_DATA: WardRecord[] = [
  {
    ward_id: 114,
    ward_name: 'Chintadripet & Pudupet',
    zone_id: 8,
    zone_name: 'Anna Nagar',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0,
    grid_lon: 80.2,
    temperature_2m: 37.8,
    relative_humidity: 68.2,
    wind_speed_10m: 2.1,
    solar_radiation: 812.0,
    tmrt: 56.4,
    utci: 42.1,
    wbgt_outdoor: 32.8,
    heat_index: 44.2,
    htsi: 74.2,
    htsi_level: 4,
    htsi_label: 'Very High',
    burden_24h: 38.5,
    burden_72h: 42.1,
    nighttime_stress: 82.4,
    is_extreme_event: false,
    population: 34200,
    area_km2: 0.68,
    population_density: 50294,
    exposure_density_norm: 0.892,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.292,
    adaptive_capacity_norm: 0.245,
    vulnerability: 0.823, // 0.5*(0.892) + 0.5*(1 - 0.245)
    heat_hazard: 0.742,
    human_heat_risk_formula_a: 0.545,
    human_heat_risk_formula_b: 0.604,
    human_heat_risk: 0.604,
    risk_level: 'Very High'
  },
  {
    ward_id: 53,
    ward_name: 'Royapuram Harbour',
    zone_id: 5,
    zone_name: 'Royapuram',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1,
    grid_lon: 80.2,
    temperature_2m: 38.2,
    relative_humidity: 71.5,
    wind_speed_10m: 1.8,
    solar_radiation: 840.0,
    tmrt: 58.2,
    utci: 43.6,
    wbgt_outdoor: 33.4,
    heat_index: 46.1,
    htsi: 76.8,
    htsi_level: 4,
    htsi_label: 'Very High',
    burden_24h: 41.2,
    burden_72h: 44.8,
    nighttime_stress: 86.0,
    is_extreme_event: false,
    population: 39500,
    area_km2: 0.72,
    population_density: 54861,
    exposure_density_norm: 0.945,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.253,
    adaptive_capacity_norm: 0.210,
    vulnerability: 0.867,
    heat_hazard: 0.768,
    human_heat_risk_formula_a: 0.629,
    human_heat_risk_formula_b: 0.678,
    human_heat_risk: 0.678,
    risk_level: 'Very High'
  },
  {
    ward_id: 48,
    ward_name: 'Vyasarpadi West',
    zone_id: 4,
    zone_name: 'Tondiarpet',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1,
    grid_lon: 80.2,
    temperature_2m: 38.0,
    relative_humidity: 69.4,
    wind_speed_10m: 2.0,
    solar_radiation: 825.0,
    tmrt: 57.1,
    utci: 42.8,
    wbgt_outdoor: 33.1,
    heat_index: 45.3,
    htsi: 73.5,
    htsi_level: 4,
    htsi_label: 'Very High',
    burden_24h: 39.0,
    burden_72h: 41.6,
    nighttime_stress: 84.1,
    is_extreme_event: false,
    population: 36800,
    area_km2: 0.75,
    population_density: 49066,
    exposure_density_norm: 0.874,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.271,
    adaptive_capacity_norm: 0.228,
    vulnerability: 0.823,
    heat_hazard: 0.735,
    human_heat_risk_formula_a: 0.528,
    human_heat_risk_formula_b: 0.584,
    human_heat_risk: 0.584,
    risk_level: 'Very High'
  },
  {
    ward_id: 73,
    ward_name: 'Perambur Barracks',
    zone_id: 6,
    zone_name: 'Thiru-Vi-Ka Nagar',
    region: 'Central',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1,
    grid_lon: 80.2,
    temperature_2m: 37.6,
    relative_humidity: 67.5,
    wind_speed_10m: 2.2,
    solar_radiation: 810.0,
    tmrt: 55.9,
    utci: 41.5,
    wbgt_outdoor: 32.4,
    heat_index: 43.8,
    htsi: 71.2,
    htsi_level: 4,
    htsi_label: 'Very High',
    burden_24h: 36.4,
    burden_72h: 39.5,
    nighttime_stress: 79.2,
    is_extreme_event: false,
    population: 32400,
    area_km2: 0.70,
    population_density: 46285,
    exposure_density_norm: 0.835,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.308,
    adaptive_capacity_norm: 0.260,
    vulnerability: 0.787,
    heat_hazard: 0.712,
    human_heat_risk_formula_a: 0.468,
    human_heat_risk_formula_b: 0.531,
    human_heat_risk: 0.531,
    risk_level: 'Very High'
  },
  {
    ward_id: 119,
    ward_name: 'Triplicane High Road',
    zone_id: 9,
    zone_name: 'Teynampet',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0,
    grid_lon: 80.2,
    temperature_2m: 37.4,
    relative_humidity: 70.1,
    wind_speed_10m: 2.4,
    solar_radiation: 795.0,
    tmrt: 55.2,
    utci: 41.8,
    wbgt_outdoor: 32.6,
    heat_index: 44.5,
    htsi: 72.0,
    htsi_level: 4,
    htsi_label: 'Very High',
    burden_24h: 37.1,
    burden_72h: 40.2,
    nighttime_stress: 81.0,
    is_extreme_event: false,
    population: 35100,
    area_km2: 0.78,
    population_density: 45000,
    exposure_density_norm: 0.816,
    healthcare_facility_count: 2,
    healthcare_facilities_per_10k: 0.569,
    adaptive_capacity_norm: 0.495,
    vulnerability: 0.660,
    heat_hazard: 0.720,
    human_heat_risk_formula_a: 0.388,
    human_heat_risk_formula_b: 0.488,
    human_heat_risk: 0.488,
    risk_level: 'High'
  },
  {
    ward_id: 84,
    ward_name: 'Ambattur Industrial Estate',
    zone_id: 7,
    zone_name: 'Ambattur',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1,
    grid_lon: 80.2,
    temperature_2m: 37.2,
    relative_humidity: 65.0,
    wind_speed_10m: 2.5,
    solar_radiation: 820.0,
    tmrt: 56.0,
    utci: 40.5,
    wbgt_outdoor: 31.8,
    heat_index: 42.6,
    htsi: 65.4,
    htsi_level: 3,
    htsi_label: 'High',
    burden_24h: 32.0,
    burden_72h: 35.1,
    nighttime_stress: 72.5,
    is_extreme_event: false,
    population: 29800,
    area_km2: 1.15,
    population_density: 25913,
    exposure_density_norm: 0.534,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.335,
    adaptive_capacity_norm: 0.285,
    vulnerability: 0.624,
    heat_hazard: 0.654,
    human_heat_risk_formula_a: 0.218,
    human_heat_risk_formula_b: 0.284,
    human_heat_risk: 0.284,
    risk_level: 'Moderate'
  },
  {
    ward_id: 130,
    ward_name: 'T. Nagar Panagal Park',
    zone_id: 10,
    zone_name: 'Kodambakkam',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0,
    grid_lon: 80.2,
    temperature_2m: 36.9,
    relative_humidity: 67.8,
    wind_speed_10m: 2.2,
    solar_radiation: 780.0,
    tmrt: 54.5,
    utci: 40.2,
    wbgt_outdoor: 31.6,
    heat_index: 42.5,
    htsi: 66.8,
    htsi_level: 3,
    htsi_label: 'High',
    burden_24h: 33.2,
    burden_72h: 36.5,
    nighttime_stress: 74.0,
    is_extreme_event: false,
    population: 31200,
    area_km2: 0.85,
    population_density: 36705,
    exposure_density_norm: 0.695,
    healthcare_facility_count: 2,
    healthcare_facilities_per_10k: 0.641,
    adaptive_capacity_norm: 0.550,
    vulnerability: 0.572,
    heat_hazard: 0.668,
    human_heat_risk_formula_a: 0.266,
    human_heat_risk_formula_b: 0.365,
    human_heat_risk: 0.365,
    risk_level: 'High'
  },
  {
    ward_id: 173,
    ward_name: 'Adyar Besant Nagar',
    zone_id: 13,
    zone_name: 'Adyar',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9,
    grid_lon: 80.2,
    temperature_2m: 35.5,
    relative_humidity: 74.2,
    wind_speed_10m: 3.8,
    solar_radiation: 760.0,
    tmrt: 52.8,
    utci: 38.6,
    wbgt_outdoor: 30.8,
    heat_index: 41.2,
    htsi: 59.8,
    htsi_level: 2,
    htsi_label: 'Moderate',
    burden_24h: 24.1,
    burden_72h: 27.5,
    nighttime_stress: 60.2,
    is_extreme_event: false,
    population: 24500,
    area_km2: 1.40,
    population_density: 17500,
    exposure_density_norm: 0.408,
    healthcare_facility_count: 2,
    healthcare_facilities_per_10k: 0.816,
    adaptive_capacity_norm: 0.710,
    vulnerability: 0.349,
    heat_hazard: 0.598,
    human_heat_risk_formula_a: 0.085,
    human_heat_risk_formula_b: 0.164,
    human_heat_risk: 0.164,
    risk_level: 'Normal'
  },
  {
    ward_id: 198,
    ward_name: 'Sholinganallur IT Expressway',
    zone_id: 15,
    zone_name: 'Sholinganallur',
    region: 'South',
    assigned_grid_id: 'grid_12.8_80.2',
    grid_lat: 12.8,
    grid_lon: 80.2,
    temperature_2m: 34.8,
    relative_humidity: 76.0,
    wind_speed_10m: 4.2,
    solar_radiation: 745.0,
    tmrt: 51.5,
    utci: 37.4,
    wbgt_outdoor: 30.1,
    heat_index: 39.8,
    htsi: 53.4,
    htsi_level: 2,
    htsi_label: 'Moderate',
    burden_24h: 18.2,
    burden_72h: 21.0,
    nighttime_stress: 51.4,
    is_extreme_event: false,
    population: 21200,
    area_km2: 2.85,
    population_density: 7438,
    exposure_density_norm: 0.258,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.471,
    adaptive_capacity_norm: 0.410,
    vulnerability: 0.424,
    heat_hazard: 0.534,
    human_heat_risk_formula_a: 0.058,
    human_heat_risk_formula_b: 0.098,
    human_heat_risk: 0.098,
    risk_level: 'Normal'
  },
  {
    ward_id: 160,
    ward_name: 'Alandur Cantonment Fringe',
    zone_id: 12,
    zone_name: 'Alandur',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9,
    grid_lon: 80.2,
    temperature_2m: 36.1,
    relative_humidity: 69.8,
    wind_speed_10m: 2.8,
    solar_radiation: 785.0,
    tmrt: 53.6,
    utci: 39.4,
    wbgt_outdoor: 31.2,
    heat_index: 41.8,
    htsi: 58.6,
    htsi_level: 2,
    htsi_label: 'Moderate',
    burden_24h: 23.5,
    burden_72h: 26.8,
    nighttime_stress: 59.0,
    is_extreme_event: false,
    population: 26800,
    area_km2: 1.25,
    population_density: 21440,
    exposure_density_norm: 0.468,
    healthcare_facility_count: 1,
    healthcare_facilities_per_10k: 0.373,
    adaptive_capacity_norm: 0.320,
    vulnerability: 0.574,
    heat_hazard: 0.586,
    human_heat_risk_formula_a: 0.157,
    human_heat_risk_formula_b: 0.216,
    human_heat_risk: 0.216,
    risk_level: 'Moderate'
  },
  // --- Expanded wards for full 200-ward dashboard representation ---
  {
    ward_id: 5,
    ward_name: 'Thiruvottiyur Theradi',
    zone_id: 1,
    zone_name: 'Thiruvottiyur',
    region: 'North',
    assigned_grid_id: 'grid_13.2_80.2',
    grid_lat: 13.2, grid_lon: 80.2,
    temperature_2m: 37.5, relative_humidity: 70.4, wind_speed_10m: 2.3, solar_radiation: 808.0, tmrt: 56.0,
    utci: 41.8, wbgt_outdoor: 32.5, heat_index: 44.0,
    htsi: 70.4, htsi_level: 3, htsi_label: 'High',
    burden_24h: 36.0, burden_72h: 39.2, nighttime_stress: 78.5, is_extreme_event: false,
    population: 28400, area_km2: 0.82, population_density: 34634, exposure_density_norm: 0.664,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.352, adaptive_capacity_norm: 0.295,
    vulnerability: 0.684, heat_hazard: 0.704,
    human_heat_risk_formula_a: 0.320, human_heat_risk_formula_b: 0.395,
    human_heat_risk: 0.395, risk_level: 'High'
  },
  {
    ward_id: 12,
    ward_name: 'Manali New Town',
    zone_id: 2,
    zone_name: 'Manali',
    region: 'North',
    assigned_grid_id: 'grid_13.2_80.2',
    grid_lat: 13.2, grid_lon: 80.2,
    temperature_2m: 36.8, relative_humidity: 66.5, wind_speed_10m: 2.6, solar_radiation: 790.0, tmrt: 54.2,
    utci: 40.2, wbgt_outdoor: 31.5, heat_index: 42.4,
    htsi: 62.8, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 30.5, burden_72h: 33.2, nighttime_stress: 68.4, is_extreme_event: false,
    population: 19200, area_km2: 1.60, population_density: 12000, exposure_density_norm: 0.325,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.520, adaptive_capacity_norm: 0.450,
    vulnerability: 0.437, heat_hazard: 0.628,
    human_heat_risk_formula_a: 0.089, human_heat_risk_formula_b: 0.149,
    human_heat_risk: 0.149, risk_level: 'Normal'
  },
  {
    ward_id: 22,
    ward_name: 'Madhavaram Milk Colony',
    zone_id: 3,
    zone_name: 'Madhavaram',
    region: 'North',
    assigned_grid_id: 'grid_13.2_80.2',
    grid_lat: 13.2, grid_lon: 80.2,
    temperature_2m: 37.0, relative_humidity: 67.2, wind_speed_10m: 2.4, solar_radiation: 800.0, tmrt: 54.8,
    utci: 40.6, wbgt_outdoor: 31.8, heat_index: 42.8,
    htsi: 64.2, htsi_level: 3, htsi_label: 'High',
    burden_24h: 31.5, burden_72h: 34.8, nighttime_stress: 70.2, is_extreme_event: false,
    population: 25600, area_km2: 1.10, population_density: 23272, exposure_density_norm: 0.494,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.390, adaptive_capacity_norm: 0.335,
    vulnerability: 0.579, heat_hazard: 0.642,
    human_heat_risk_formula_a: 0.184, human_heat_risk_formula_b: 0.252,
    human_heat_risk: 0.252, risk_level: 'Moderate'
  },
  {
    ward_id: 42,
    ward_name: 'Tondiarpet High Road',
    zone_id: 4,
    zone_name: 'Tondiarpet',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1, grid_lon: 80.2,
    temperature_2m: 38.1, relative_humidity: 70.8, wind_speed_10m: 1.9, solar_radiation: 835.0, tmrt: 57.8,
    utci: 43.2, wbgt_outdoor: 33.2, heat_index: 45.8,
    htsi: 75.6, htsi_level: 4, htsi_label: 'Very High',
    burden_24h: 40.2, burden_72h: 43.5, nighttime_stress: 85.2, is_extreme_event: false,
    population: 38200, area_km2: 0.68, population_density: 56176, exposure_density_norm: 0.958,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.261, adaptive_capacity_norm: 0.218,
    vulnerability: 0.870, heat_hazard: 0.756,
    human_heat_risk_formula_a: 0.631, human_heat_risk_formula_b: 0.676,
    human_heat_risk: 0.676, risk_level: 'Very High'
  },
  {
    ward_id: 58,
    ward_name: 'Royapuram Fishing Harbour',
    zone_id: 5,
    zone_name: 'Royapuram',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1, grid_lon: 80.2,
    temperature_2m: 37.9, relative_humidity: 72.0, wind_speed_10m: 2.0, solar_radiation: 830.0, tmrt: 57.4,
    utci: 42.9, wbgt_outdoor: 33.0, heat_index: 45.4,
    htsi: 74.8, htsi_level: 4, htsi_label: 'Very High',
    burden_24h: 39.5, burden_72h: 42.8, nighttime_stress: 84.0, is_extreme_event: false,
    population: 41200, area_km2: 0.78, population_density: 52820, exposure_density_norm: 0.920,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.242, adaptive_capacity_norm: 0.200,
    vulnerability: 0.860, heat_hazard: 0.748,
    human_heat_risk_formula_a: 0.591, human_heat_risk_formula_b: 0.641,
    human_heat_risk: 0.641, risk_level: 'Very High'
  },
  {
    ward_id: 78,
    ward_name: 'Kolathur Junction',
    zone_id: 6,
    zone_name: 'Thiru-Vi-Ka Nagar',
    region: 'Central',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1, grid_lon: 80.2,
    temperature_2m: 37.4, relative_humidity: 68.0, wind_speed_10m: 2.1, solar_radiation: 805.0, tmrt: 55.6,
    utci: 41.2, wbgt_outdoor: 32.2, heat_index: 43.5,
    htsi: 69.8, htsi_level: 3, htsi_label: 'High',
    burden_24h: 35.2, burden_72h: 38.4, nighttime_stress: 77.0, is_extreme_event: false,
    population: 33800, area_km2: 0.85, population_density: 39764, exposure_density_norm: 0.742,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.295, adaptive_capacity_norm: 0.250,
    vulnerability: 0.746, heat_hazard: 0.698,
    human_heat_risk_formula_a: 0.386, human_heat_risk_formula_b: 0.453,
    human_heat_risk: 0.453, risk_level: 'High'
  },
  {
    ward_id: 91,
    ward_name: 'Ambattur OT Bus Stand',
    zone_id: 7,
    zone_name: 'Ambattur',
    region: 'North',
    assigned_grid_id: 'grid_13.1_80.2',
    grid_lat: 13.1, grid_lon: 80.2,
    temperature_2m: 37.0, relative_humidity: 64.8, wind_speed_10m: 2.6, solar_radiation: 815.0, tmrt: 55.5,
    utci: 40.0, wbgt_outdoor: 31.4, heat_index: 42.0,
    htsi: 63.5, htsi_level: 3, htsi_label: 'High',
    burden_24h: 30.8, burden_72h: 33.6, nighttime_stress: 69.0, is_extreme_event: false,
    population: 27400, area_km2: 1.05, population_density: 26095, exposure_density_norm: 0.540,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.365, adaptive_capacity_norm: 0.310,
    vulnerability: 0.615, heat_hazard: 0.635,
    human_heat_risk_formula_a: 0.211, human_heat_risk_formula_b: 0.278,
    human_heat_risk: 0.278, risk_level: 'Moderate'
  },
  {
    ward_id: 105,
    ward_name: 'Anna Nagar East',
    zone_id: 8,
    zone_name: 'Anna Nagar',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0, grid_lon: 80.2,
    temperature_2m: 37.2, relative_humidity: 66.8, wind_speed_10m: 2.3, solar_radiation: 800.0, tmrt: 55.0,
    utci: 40.8, wbgt_outdoor: 31.9, heat_index: 43.0,
    htsi: 67.5, htsi_level: 3, htsi_label: 'High',
    burden_24h: 33.8, burden_72h: 37.0, nighttime_stress: 74.8, is_extreme_event: false,
    population: 30200, area_km2: 0.92, population_density: 32826, exposure_density_norm: 0.638,
    healthcare_facility_count: 2, healthcare_facilities_per_10k: 0.662, adaptive_capacity_norm: 0.570,
    vulnerability: 0.534, heat_hazard: 0.675,
    human_heat_risk_formula_a: 0.230, human_heat_risk_formula_b: 0.328,
    human_heat_risk: 0.328, risk_level: 'Moderate'
  },
  {
    ward_id: 122,
    ward_name: 'Mylapore Kapaleeshwarar',
    zone_id: 9,
    zone_name: 'Teynampet',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0, grid_lon: 80.2,
    temperature_2m: 37.6, relative_humidity: 71.2, wind_speed_10m: 2.5, solar_radiation: 800.0, tmrt: 55.8,
    utci: 42.0, wbgt_outdoor: 32.7, heat_index: 44.8,
    htsi: 72.8, htsi_level: 4, htsi_label: 'Very High',
    burden_24h: 37.8, burden_72h: 40.8, nighttime_stress: 81.5, is_extreme_event: false,
    population: 36500, area_km2: 0.82, population_density: 44512, exposure_density_norm: 0.808,
    healthcare_facility_count: 2, healthcare_facilities_per_10k: 0.547, adaptive_capacity_norm: 0.475,
    vulnerability: 0.666, heat_hazard: 0.728,
    human_heat_risk_formula_a: 0.392, human_heat_risk_formula_b: 0.481,
    human_heat_risk: 0.481, risk_level: 'High'
  },
  {
    ward_id: 135,
    ward_name: 'Kodambakkam West Mambalam',
    zone_id: 10,
    zone_name: 'Kodambakkam',
    region: 'Central',
    assigned_grid_id: 'grid_13.0_80.2',
    grid_lat: 13.0, grid_lon: 80.2,
    temperature_2m: 36.8, relative_humidity: 68.5, wind_speed_10m: 2.3, solar_radiation: 778.0, tmrt: 54.2,
    utci: 39.8, wbgt_outdoor: 31.4, heat_index: 42.0,
    htsi: 65.2, htsi_level: 3, htsi_label: 'High',
    burden_24h: 32.0, burden_72h: 35.2, nighttime_stress: 72.4, is_extreme_event: false,
    population: 29600, area_km2: 0.78, population_density: 37948, exposure_density_norm: 0.714,
    healthcare_facility_count: 2, healthcare_facilities_per_10k: 0.675, adaptive_capacity_norm: 0.580,
    vulnerability: 0.567, heat_hazard: 0.652,
    human_heat_risk_formula_a: 0.264, human_heat_risk_formula_b: 0.354,
    human_heat_risk: 0.354, risk_level: 'High'
  },
  {
    ward_id: 148,
    ward_name: 'Valasaravakkam Arcot Road',
    zone_id: 11,
    zone_name: 'Valasaravakkam',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9, grid_lon: 80.2,
    temperature_2m: 36.2, relative_humidity: 70.0, wind_speed_10m: 2.8, solar_radiation: 770.0, tmrt: 53.4,
    utci: 39.2, wbgt_outdoor: 31.0, heat_index: 41.5,
    htsi: 60.4, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 25.8, burden_72h: 28.5, nighttime_stress: 62.5, is_extreme_event: false,
    population: 24200, area_km2: 1.20, population_density: 20166, exposure_density_norm: 0.448,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.413, adaptive_capacity_norm: 0.355,
    vulnerability: 0.546, heat_hazard: 0.604,
    human_heat_risk_formula_a: 0.148, human_heat_risk_formula_b: 0.210,
    human_heat_risk: 0.210, risk_level: 'Moderate'
  },
  {
    ward_id: 165,
    ward_name: 'Guindy Industrial',
    zone_id: 12,
    zone_name: 'Alandur',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9, grid_lon: 80.2,
    temperature_2m: 36.4, relative_humidity: 68.2, wind_speed_10m: 2.6, solar_radiation: 782.0, tmrt: 53.8,
    utci: 39.6, wbgt_outdoor: 31.3, heat_index: 42.0,
    htsi: 61.8, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 27.2, burden_72h: 30.0, nighttime_stress: 64.5, is_extreme_event: false,
    population: 22800, area_km2: 1.35, population_density: 16888, exposure_density_norm: 0.398,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.438, adaptive_capacity_norm: 0.380,
    vulnerability: 0.509, heat_hazard: 0.618,
    human_heat_risk_formula_a: 0.125, human_heat_risk_formula_b: 0.186,
    human_heat_risk: 0.186, risk_level: 'Normal'
  },
  {
    ward_id: 178,
    ward_name: 'Velachery Lake View',
    zone_id: 13,
    zone_name: 'Adyar',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9, grid_lon: 80.2,
    temperature_2m: 35.8, relative_humidity: 73.5, wind_speed_10m: 3.4, solar_radiation: 758.0, tmrt: 52.4,
    utci: 38.4, wbgt_outdoor: 30.6, heat_index: 40.8,
    htsi: 58.2, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 22.8, burden_72h: 25.6, nighttime_stress: 58.0, is_extreme_event: false,
    population: 27200, area_km2: 1.50, population_density: 18133, exposure_density_norm: 0.418,
    healthcare_facility_count: 2, healthcare_facilities_per_10k: 0.735, adaptive_capacity_norm: 0.640,
    vulnerability: 0.389, heat_hazard: 0.582,
    human_heat_risk_formula_a: 0.094, human_heat_risk_formula_b: 0.162,
    human_heat_risk: 0.162, risk_level: 'Normal'
  },
  {
    ward_id: 188,
    ward_name: 'Perungudi Taramani',
    zone_id: 14,
    zone_name: 'Perungudi',
    region: 'South',
    assigned_grid_id: 'grid_12.9_80.2',
    grid_lat: 12.9, grid_lon: 80.2,
    temperature_2m: 35.4, relative_humidity: 75.0, wind_speed_10m: 3.6, solar_radiation: 750.0, tmrt: 51.8,
    utci: 37.8, wbgt_outdoor: 30.2, heat_index: 40.2,
    htsi: 55.6, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 20.4, burden_72h: 23.2, nighttime_stress: 54.5, is_extreme_event: false,
    population: 20800, area_km2: 2.10, population_density: 9904, exposure_density_norm: 0.296,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.480, adaptive_capacity_norm: 0.418,
    vulnerability: 0.439, heat_hazard: 0.556,
    human_heat_risk_formula_a: 0.072, human_heat_risk_formula_b: 0.120,
    human_heat_risk: 0.120, risk_level: 'Normal'
  },
  {
    ward_id: 195,
    ward_name: 'Sholinganallur Karapakkam',
    zone_id: 15,
    zone_name: 'Sholinganallur',
    region: 'South',
    assigned_grid_id: 'grid_12.8_80.2',
    grid_lat: 12.8, grid_lon: 80.2,
    temperature_2m: 34.6, relative_humidity: 76.5, wind_speed_10m: 4.4, solar_radiation: 742.0, tmrt: 51.0,
    utci: 37.0, wbgt_outdoor: 29.8, heat_index: 39.4,
    htsi: 51.8, htsi_level: 2, htsi_label: 'Moderate',
    burden_24h: 16.8, burden_72h: 19.5, nighttime_stress: 49.0, is_extreme_event: false,
    population: 18500, area_km2: 3.20, population_density: 5781, exposure_density_norm: 0.218,
    healthcare_facility_count: 1, healthcare_facilities_per_10k: 0.540, adaptive_capacity_norm: 0.470,
    vulnerability: 0.374, heat_hazard: 0.518,
    human_heat_risk_formula_a: 0.042, human_heat_risk_formula_b: 0.078,
    human_heat_risk: 0.078, risk_level: 'Normal'
  }
];

// Today's current conditions for the forecast strip
export const FORECAST_TODAY: ForecastDay = {
  day_offset: 0,
  date: '10 Sep 2026',
  day_name: 'Today',
  max_temperature: 38.2,
  min_temperature: 28.4,
  avg_rh: 71.5,
  max_wind_speed: 2.4,
  max_utci: 43.6,
  max_wbgt: 33.4,
  max_htsi: 76.8,
  risk_level: 'Very High',
  nighttime_stress_flag: true,
  ml_lead_mae_temp: 0.0,
  ml_lead_mae_htsi: 0.0
};

export const FORECAST_DAYS: ForecastDay[] = [
  {
    day_offset: 1,
    date: '11 Sep 2026',
    day_name: 'Tomorrow',
    max_temperature: 38.4,
    min_temperature: 28.2,
    avg_rh: 72.4,
    max_wind_speed: 2.8,
    max_utci: 43.1,
    max_wbgt: 33.2,
    max_htsi: 75.4,
    risk_level: 'Very High',
    nighttime_stress_flag: true,
    ml_lead_mae_temp: 0.85,
    ml_lead_mae_htsi: 3.02
  },
  {
    day_offset: 2,
    date: '12 Sep 2026',
    day_name: 'Saturday',
    max_temperature: 39.1,
    min_temperature: 28.6,
    avg_rh: 70.1,
    max_wind_speed: 2.4,
    max_utci: 44.5,
    max_wbgt: 33.8,
    max_htsi: 77.2,
    risk_level: 'Very High',
    nighttime_stress_flag: true,
    ml_lead_mae_temp: 0.88,
    ml_lead_mae_htsi: 3.18
  },
  {
    day_offset: 3,
    date: '13 Sep 2026',
    day_name: 'Sunday',
    max_temperature: 39.8,
    min_temperature: 29.1,
    avg_rh: 68.5,
    max_wind_speed: 2.1,
    max_utci: 45.8,
    max_wbgt: 34.4,
    max_htsi: 79.5,
    risk_level: 'Very High',
    nighttime_stress_flag: true,
    ml_lead_mae_temp: 0.92,
    ml_lead_mae_htsi: 3.36
  },
  {
    day_offset: 4,
    date: '14 Sep 2026',
    day_name: 'Monday',
    max_temperature: 37.6,
    min_temperature: 27.9,
    avg_rh: 74.8,
    max_wind_speed: 3.5,
    max_utci: 41.2,
    max_wbgt: 32.1,
    max_htsi: 68.9,
    risk_level: 'High',
    nighttime_stress_flag: false,
    ml_lead_mae_temp: 0.93,
    ml_lead_mae_htsi: 3.39
  },
  {
    day_offset: 5,
    date: '15 Sep 2026',
    day_name: 'Tuesday',
    max_temperature: 36.2,
    min_temperature: 27.4,
    avg_rh: 77.2,
    max_wind_speed: 4.1,
    max_utci: 39.5,
    max_wbgt: 31.2,
    max_htsi: 61.2,
    risk_level: 'Moderate',
    nighttime_stress_flag: false,
    ml_lead_mae_temp: 0.95,
    ml_lead_mae_htsi: 3.45
  }
];

export const ALERT_PROTOCOLS: AlertProtocol[] = [
  {
    level: 'Normal',
    color_hex: '#10b981',
    htsi_range: 'HTSI < 50.0 (Below P50)',
    utci_range: 'UTCI < 26.0°C (No Thermal Stress)',
    status_summary: 'Normal baseline thermal conditions. Standard municipal operations and public activity permitted without restriction.',
    gcc_administration: [
      'Maintain standard civic water points at bus termini and transit junctions.',
      'Regular routine maintenance of park misting stations and public fountains.'
    ],
    uphc_healthcare: [
      'Standard surveillance for routine dehydration in maternal and infant clinics.',
      'Stock ORS replenishment per monthly quota.'
    ],
    labor_contractors: [
      'Standard 8-hour construction shifts with regular hydration breaks.',
      'Ensure basic on-site clean potable water availability.'
    ],
    vulnerable_public: [
      'Standard daily fluid intake (2 to 2.5 litres).',
      'Normal outdoor movement.'
    ],
    tamil_summary: 'வழக்கமான வெப்பநிலை சூழல். இயல்பான பொதுப் பணிகள் தொடரலாம்.'
  },
  {
    level: 'Moderate',
    color_hex: '#f59e0b',
    htsi_range: 'HTSI 50.0 – 65.0 (P50 to P75)',
    utci_range: 'UTCI 26.0°C – 32.0°C (Moderate Heat Stress)',
    status_summary: 'Elevated thermal discomfort. Precautionary monitoring for outdoor laborers and geriatric residents across urban heat islands.',
    gcc_administration: [
      'Deploy inspection squads to ensure worksite shade and drinking water in construction corridors.',
      'Increase inspection of municipal water distribution tankers across high-density wards.'
    ],
    uphc_healthcare: [
      'Alert urban health nurses to monitor elderly patients with cardiovascular conditions during home visits.',
      'Verify buffer stocks of zinc and rehydration salts in UPHC dispensaries.'
    ],
    labor_contractors: [
      'Mandate 15-minute shaded rest breaks every 2 hours of heavy outdoor exertion.',
      'Provide covered rest tarpaulins on construction scaffolding.'
    ],
    vulnerable_public: [
      'Increase hydration to 3 litres daily; carry umbrella or head covering between 11:00 and 15:00 IST.',
      'Limit high-intensity sports or jogging during midday peak hours.'
    ],
    tamil_summary: 'மிதமான வெப்ப அழுத்தம். முதியவர்கள் மற்றும் வெளிப்புறப் பணியாளர்கள் தகுந்த நீர் அருந்தி எச்சரிக்கையுடன் செயல்படவும்.'
  },
  {
    level: 'High',
    color_hex: '#f97316',
    htsi_range: 'HTSI 65.0 – 72.0 (P75 to P90)',
    utci_range: 'UTCI 32.0°C – 38.0°C (Strong Heat Stress)',
    status_summary: 'Strong physiological strain. Heightened risk of heat cramps and exhaustion. Active intervention required in dense urban wards.',
    gcc_administration: [
      'Activate designated public air-cooled shelters (community halls, library reading rooms) 11:00 to 17:00 IST.',
      'Operate mobile water misting tankers along high-pedestrian corridors (Ranganathan Street, Broadway, Central Station).',
      'Display real-time HTSI heat advisories on all electronic Variable Message Signs (VMS) on city arterial roads.'
    ],
    uphc_healthcare: [
      'Establish a designated heat-triage bed in each UPHC equipped with cooling fans and oral rehydration supplies.',
      'Ensure 108 Emergency Ambulance service has pre-positioned ice packs and IV normal saline.'
    ],
    labor_contractors: [
      'Mandatory suspension of direct-sun unshaded manual labor between 12:00 and 15:00 IST.',
      'Supply chilled electrolyte/butter-milk solutions to site workers at contractor expense.'
    ],
    vulnerable_public: [
      'Senior citizens (65+) and infants must stay indoors in ventilated or shaded rooms.',
      'Avoid caffeinated, alcoholic, or heavy sugary beverages that accelerate dehydration.'
    ],
    tamil_summary: 'அதிக வெப்ப அழுத்தம். நண்பகல் 12 மணி முதல் பிற்பகல் 3 மணி வரை கடுமையான வெயிலில் வேலை செய்வதை தவிர்க்கவும்.'
  },
  {
    level: 'Very High',
    color_hex: '#ef4444',
    htsi_range: 'HTSI 72.0 – 80.0 (P90 to P97.5)',
    utci_range: 'UTCI 38.0°C – 46.0°C (Very Strong Heat Stress)',
    status_summary: 'Severe municipal heat hazard. High probability of heat exhaustion and impending heat stroke across exposed populations.',
    gcc_administration: [
      'Issue emergency municipal order enforcing complete halt of outdoor construction and road surfacing 11:30 to 15:30 IST.',
      'Deploy GCC water-sprinkling tankers across dense wards in Royapuram, Tondiarpet, and Thiru-Vi-Ka Nagar.',
      'Extend open hours of major city parks (Semmozhi Poonga, Nageswara Rao Park) until 22:00 IST for night cooling relief.'
    ],
    uphc_healthcare: [
      'Mobilize rapid medical response teams at GCC regional dispensaries; 24/7 staffing of heat stroke emergency beds.',
      'Track daily ward-level heat exhaustion admissions and upload data to the HeatPulse surveillance dashboard.'
    ],
    labor_contractors: [
      'Enforce full work stoppage during midday hours without wage deduction under GCC Disaster Management regulations.',
      'Conduct mandatory morning vital checks (pulse, dizziness check) for all industrial and sanitation workers.'
    ],
    vulnerable_public: [
      'Strictly avoid direct sunlight; use wet cloths/sponges for cooling if air conditioning is unavailable.',
      'Immediately report signs of heat stroke (cessation of sweating, confusion, nausea, body temp > 103°F) to 108.'
    ],
    tamil_summary: 'மிக அதிக வெப்ப அபாயம்! அவசர சுகாதார எச்சரிக்கை. வெளிப்புற உடலுழைப்பு மதிய வேளையில் முழுமையாக தடை செய்யப்படுகிறது.'
  },
  {
    level: 'Extreme',
    color_hex: '#7c3aed',
    htsi_range: 'HTSI > 80.0 (Above P97.5) or UTCI ≥ 46.0°C',
    utci_range: 'UTCI ≥ 46.0°C (Extreme Thermal Strain)',
    status_summary: 'Catastrophic thermal strain. Life-threatening physiological heat load with rapid onset of hyperthermia and circulatory failure.',
    gcc_administration: [
      'Activate Municipal Disaster Management Heat Emergency Protocol under District Collector & GCC Commissioner.',
      'Deploy civil defense volunteers and home guards for emergency door-to-door welfare checks on isolated elderly.',
      'Coordinate with TANGEDCO to guarantee uninterrupted power supply to primary medical centers and pumping stations.',
      'Public transport buses instructed to operate shaded holding points.'
    ],
    uphc_healthcare: [
      'Declare Level 1 Mass Casualty triage readiness across all GCC tertiary and district hospitals (Rajiv Gandhi GH, Kilpauk, Stanley).',
      'Immediate whole-body ice-water immersion capabilities active for admitted heat hyperpyrexia cases.'
    ],
    labor_contractors: [
      'Complete, legally mandated cessation of all non-emergency outdoor labor; violators subject to immediate municipal penal action.'
    ],
    vulnerable_public: [
      'Code Red Emergency: All citizens instructed to remain in coolest accessible indoor spaces.',
      'Contact GCC Emergency Helpline 1913 or Health Hotline 104 immediately for assistance.'
    ],
    tamil_summary: 'தீவிர பெருவெப்ப அவசரநிலை! உயிருக்கு ஆபத்தான வெப்ப சூழல். பொதுமக்கள் அனைவரும் பாதுகாப்பான குளிர்ந்த இடங்களில் இருக்கவும்.'
  }
];
